version: "3.9"

services:
  gnuradio:
    image: sar-ai-tools:latest
    container_name: sar-ai-tools
    network_mode : "host"
    privileged: true    
    volumes:
      - /home/tom/git/sar-ai/acquisition/data/raw/1645382604:/input
      - ./labelling:/tools/labelling
      - ./plotting:/tools/plotting
      - ./learning:/tools/learning
    environment:
      - DISPLAY
    command: gnuradio-companion