version: "3.9"

services:
  gnuradio:
    image: sar-ai-tools:latest
    container_name: sar-ai-tools
    network_mode : "host"
    privileged: true    
    volumes:
      - /home/tom/git/sar-ai/acquisition/data/:/input
      - ./labelling:/tools/labelling
      - ./plotting:/tools/plotting
    environment:
      - DISPLAY
    command: gnuradio-companion